version: '3.7'

services:
  couchbase:
    build:
      context: ./
      dockerfile: ./Dockerfile.couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
#    networks:
#      - my_network
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_PASSWORD=

  spring-boot:
    image: spring-boot-custom
    ports:
      - 8080:8080
#    networks:
#      - my_network
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_PASSWORD=
#    depends_on:
#      - couchbase
    restart: always


#networks:
#  my_network:
#    driver: bridge
